version: '3'

services:
  postgresql:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - pg-network
    env_file:
      - .env
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data
      - ${FOLDER_PATH}/init_full_db.sql:/docker-entrypoint-initdb.d/init_full_db.sql


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on: 
      - postgresql
    networks:
      - pg-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  pg-network:

volumes:
  pgadmin-data: