name: Aissyr Streamlit Version

on:
  push:
    branches: ["App_Streamlit"]
  pull_request:
    branches: ["App_Streamlit"]

permissions:
  contents: read

jobs:
  streamlit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Show environment variables
        run: |
          env

      - name: Run Streamlit tests
        uses: streamlit/streamlit-app-action@v0.0.3
        with:
          app-path: Home.py
          skip-smoke: true
