name: Aissyr Streamlit Version

on:
  push:
    branches: ["App_Streamlit"]
  pull_request:
    branches: ["App_Streamlit"]

permissions:
  contents: read

jobs:
  streamlit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: streamlit/streamlit-app-action@v0.0.3
        with:
          app-path: Home.py
      - if: always()
        uses: pmeier/pytest-results-actions@v0.6.0
        with:
          path: test-results.xml
          summary: true
          display-options: fEX
